version: '3.8'
services:
  whatsapp: 
    image: taufikdev88/simplewhatsappapi:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/app/data